apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: storage-operator
  template:
    metadata:
      labels:
        name: storage-operator
    spec:
      serviceAccountName: storage-operator
      containers:
        - name: storage-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - storage-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ''
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "storage-operator"
